
[env:esp32-s3-n16r8]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_upload.flash_size = 16MB
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.arduino.memory_type = qio_opi
board_build.partitions = default_16MB.csv

build_unflags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1

extra_scripts = pre:version_script.py

build_flags =
    -DBOARD_HAS_PSRAM
    -mfix-esp32-psram-cache-issue
    -DARDUINO_USB_MODE=0
    -DARDUINO_USB_CDC_ON_BOOT=0

lib_deps =
    fortyseveneffects/MIDI Library
    tttapa/Control Surface@^2.1.0
    adafruit/Adafruit SSD1306
    adafruit/Adafruit GFX Library
    h2zero/NimBLE-Arduino@^2.1.3

[env:native]
platform = native
test_framework = unity
test_filter = native/test_ccstatestore_props, native/test_bleprotocol_props, native/test_main, native/test_integration_props
test_build_src = true
build_flags =
    -std=c++14
    -DRC_MAX_SUCCESS=100
    -Itest/native/mocks
    -Isrc
build_src_filter =
    +<ble/CCStateStore.cpp>
    +<ble/BleProtocol.cpp>
lib_deps =
    https://github.com/emil-e/rapidcheck.git

[env:native_bleserver]
platform = native
test_framework = unity
test_filter = native/test_bleserver_unit
test_build_src = true
build_flags =
    -std=c++14
    -Itest/native/mocks
    -Isrc
build_src_filter =
    +<ble/CCStateStore.cpp>
    +<ble/BleProtocol.cpp>

[env:native_bleserver_connection]
platform = native
test_framework = unity
test_filter = native/test_bleserver_connection
test_build_src = true
build_flags =
    -std=c++14
    -Itest/native/mocks
    -Isrc
build_src_filter =
    +<ble/CCStateStore.cpp>
    +<ble/BleProtocol.cpp>

[env:native_integration]
platform = native
test_framework = unity
test_filter = native/test_integration_props
test_build_src = true
build_flags =
    -std=c++14
    -fabi-version=0
    -DRC_MAX_SUCCESS=100
    -Itest/native/mocks
    -Isrc
build_src_filter =
    +<ble/CCStateStore.cpp>
    +<ble/BleProtocol.cpp>
lib_deps =
    https://github.com/emil-e/rapidcheck.git
